language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t adrianbogdann/docker-react -f Dockerfile.dev .

script: 
  - docker run -e CI=true adrianbogdann/docker-react npm run test